### ISSUE TITLE
【BattleScene】武器による通常攻撃範囲を計算するクラスの作成

### ISSUE THREAD

**Issue by imadoki** [ProjectKidona/game#148]
武器の範囲パターンID，ユニットの位置を受け取って，攻撃範囲をMapMatrixで返す

**Comment by imadoki** [comment]
色々考え、ちょっと実装を変えました

作ったものとしては以下の通りです
+ 攻撃範囲を表現するクラス
  - csv形式のファイルから攻撃範囲を受け取ってMapMatrixで返します
+ 上記のクラスからattackableMapを設定するメソッド (in AttackSelectState)
+ attackableMapからregionMapを作成するメソッド  (in AttackSelectState)
+ AttackSelectStateのデストラクタにてattackableMapを解放するように修正

**Comment by sho7midori** [comment]
いくつか確認したいことがあります。
- 攻撃可能なマスがマップからはみ出している場合を考慮してありますか？
    - 例：ユニット位置(0, 0)のとき、通常攻撃範囲を求めると(-1, 0), (0, -1), (0, 1), (1, 0)となるが、このときマイナス座標の処理はどうしていますか？

- このクラスは将来的に特技の範囲（攻撃、回復、補助）の生成に応用できますか？

あと、これは「できれば」の話ですが・・・
- CSVデータの読み込みにはぜひDataReaderを使って欲しいです。
    - ただし、"u"をどう処理してくれるかは未確認です（エラー吐くかもしれないし、ASCIIコード117を返してくれるかもしれない）

確認よろしくお願いします。

**Comment by imadoki** [comment]
> 攻撃可能なマスがマップからはみ出している場合を考慮してありますか？
考慮しています．

AttackRegionクラスから攻撃可能な範囲を取得して，BattleSceneのregionMapに登録するMapMatrixを生成する際に，Mapの範囲外にある攻撃可能マスは無視するよう処理しています．

> 特技の範囲の生成に応用できますか？

新たに作成したAttackRegionクラスはcsvファイルから読みだした攻撃可能範囲と自ユニットの位置を表現するクラスです．攻撃可能範囲はMapMatrixで，自ユニットの位置はx, y座標で返すことが出来ます．　　
ただ，返ってきた攻撃可能範囲を表すMapMatrixと自ユニットの位置から，regionMapを作成するメソッドはAttackSelectStateに実装してしまったので，特技用のregionMapを生成するメソッドは別に作る必要がありそうです．

もしくは，AttackRegionクラスにattackableMapとregionMap用のMapMatrixを作成するメソッドを用意した方がいいのかも?

> CSVデータの読み込みにはDataReaderを使う

了解です．修正します．

**Comment by sho7midori** [comment]
回答有難うございます。

AttackRegionクラスは、CSVを読み込んで全体マップに対する攻撃範囲（attackableMap?）を生成するものではないのですね。（AttackableMapを生成するのはAttackSelectState::calcAttackable?）

個人的には、calcAttackable()の機能はAttackRegionに含めてもいいのではないか。と思うのですが、いかがでしょうか。

**Comment by sho7midori** [comment]
また、範囲クラスに関して、私は以下のように考えています。参考になれば幸いです。
意味不明であれば無視して下さい。

- プログラム上の色々なところで外部ファイルを読みに行くと、ファイルパス修正時に大変なことになるので、出来ればBattleSceneのinit()で外部ファイル読み込みは全て終わらせたい。
    - BattleScene::init()でAttackRegionを生成して、場合に応じてBattleSceneからgetする方法
        - この時、AttackRegionは、MapMatrix（attackableMap）のラッパー？になる
        - 例えば、武器クラスを作成して、これに武器に関する情報をもたせた場合、範囲情報はAttackRegion型になる

- 「範囲」を持つものとしてより一般的なクラスを作成する
    - 範囲は主に「移動範囲(movableMap)、攻撃範囲（attackableMap）、特技、特性範囲」の3つ
    - これらを包括的に扱えるようなクラスがあってもいいのではないか。
        - これはちょっとやりすぎかもしれないです・・・

**Comment by imadoki** [comment]
> calcAttackable()の機能はAttackRegionに含める

賛成です．calcAttackable()はAttackRegion側に実装します．
AttackSelectRegion側でattackableMapを持っていると，calcAttacableで生成した新しいMapMatrixで古いattackableMapを上書きしてメモリリークしそうなので
attackableMapの代わりにAttackRegionをAttackeSelectStateに持たせようかと考えています.

同様にregionMapに登録するMapMatrixを生成する機能もAttackRegionに持たせられそうですね
regionMapはDrawableMapなので，上記の上書きの問題も無さそうです

**Comment by imadoki** [comment]
> 「範囲」を持つものとしてより一般的なクラスを作成する

攻撃範囲，特技範囲，特性範囲はほとんど共通化出来そうですね．
ただ，移動範囲に関しては，移動力の計算によって出力しているので，他の3つとは少し違うものになりそう.
範囲としてregionMap用のMapMatrixを返す機能や，範囲を示すMapMatrixを返す機能あたりは共通化出来そうですが

**Comment by imadoki** [comment]
+ 範囲を保持する機能
+ 保持している範囲，その他の座標から，ステージマップ上の範囲座標を返す機能
  * 現在のattackableMapを返す機能
+ ステージマップ上の範囲座標からDrawableMap用のMapMatrixを生成し返す機能
  * 現在のregionMapへのMapMatrixを返す機能

あたりは攻撃・特技・特性で同じものを使用できそう．

**Comment by imadoki** [comment]
> BattleSceneのinit()で外部ファイル読み込みは全て終わらせたい。

了解です．AttackRegionのunordered_mapあたりとして持たせればいいですか?

**Comment by sho7midori** [comment]
生成と解放処理を正しく行いたいので、AttackRegion用のunordered_mapのラッパークラスを作って
デストラクタで持っている範囲オブジェクトを全てdeleteするようにした方がいいと思います。

**Comment by imadoki** [comment]
了解です．

ちょっとやることが増えてきたのでまとめます

+ attackableMap, regionMapの生成機能はAttackRegion側に付ける
+ AttackRegionはBattleScene::init()で一括で読み込む
+ BattleSceneに持たせるためunordered_mapのラッパークラスを作成し，これをBattleSceneに持たせる

使いまわすための汎化とかは，特技・特性側が欲しているモノの詳細がわからないので，
ちょっと置いておこうと思います

**Comment by sho7midori** [comment]
よろしくお願いします。
バトルに関して分からないことがあれば、私や@tunehoに聞いて下さい。
